# Generated by Django 3.1.3 on 2022-06-13 20:08

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('faixas', '0003_auto_20220608_1635'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caminho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atividade', models.CharField(max_length=255)),
                ('objetivo', models.CharField(max_length=255)),
                ('sequencia', models.IntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='atividade', unique=True)),
                ('faixa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='faixas.faixa')),
            ],
            options={
                'ordering': ('faixa', 'sequencia'),
            },
        ),
    ]
