# Generated by Django 3.1.3 on 2022-06-13 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caminhos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='caminho',
            name='detalhe',
            field=models.TextField(blank=True),
        ),
    ]
