# Generated by Django 3.1.3 on 2022-06-07 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faixas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faixa',
            name='ordem',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='faixa',
            name='cor_faixa',
            field=models.CharField(max_length=20),
        ),
    ]
