# Generated by Django 3.1.3 on 2022-06-08 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faixas', '0002_auto_20220607_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faixa',
            name='cor_faixa',
            field=models.ImageField(blank=True, upload_to='faixas/%Y/%m/%d'),
        ),
    ]
